env:
  browser: false
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin'
  - 'prettier'
  - 'jest'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
rules:
  'prettier/prettier': 'error'
  'eslint-plugin/no-deprecated-report-api': 'error'
ignorePatterns:
  - 'node_modules'
  - 'dist'
