name: CI

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run checks
        run: scripts/check.sh
